theme = "fleet_dark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# Save immediately in normal mode
C-s = ":w"
D = "kill_to_line_end"
X = "extend_line_above"

[keys.insert]
# In insert mode: exit to normal, make an undo point, and save
C-s = ["normal_mode", "commit_undo_checkpoint", ":write"]

[editor.auto-save]
# Only save when in insert mode
after-delay.timeout = 300
focus-lost=true
after-delay.enable = true
