theme = "fleet_dark"

[editor]
line-number = "relative"
evil = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
 
[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
Cmd-s = ":w"
D = "kill_to_line_end" 
X = "extend_line_above" 
# move lines up and down holding Ctrl
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
 
[keys.insert]
# In insert mode, escape to normal, save, and return to insert
Cmd-s = ["normal_mode", ":w", "insert_mode"]
